name: Deploy Laravel (SSH)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ssh_key   # ton environment GitHub

    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy on Azure VM
        run: |
          VM_USER="anasnadi"
          VM_IP="4.233.147.103"
          PROJECT_DIR="/home/anasnadi/git/project/formation_git/laravel"   # 🔥 A MODIFIER

          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "
            set -e

            echo '✅ Connecté au serveur'
            cd $PROJECT_DIR

            echo '📥 Git pull'
            git pull

            echo '📦 Composer install'
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo '🧹 Laravel cache clear'
            php artisan optimize:clear

            echo '⚡ Laravel optimize'
            php artisan optimize

            echo '🔁 Restart PHP (si existe)'
            sudo systemctl restart php8.2-fpm || true

            echo '✅ Déploiement terminé'
          "
