name: SSH Test Azure VM

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    environment: Production   # <-- important

    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}  # exact nom du secret

      - name: Test SSH Connection
        run: |
          SERVER_IP="4.233.147.103"
          USER="anasnadi"

          ssh -o StrictHostKeyChecking=no $USER@$SERVER_IP bash -c "
            echo '✅ SSH depuis GitHub Actions OK'
            hostname
            whoami
          "
